### CALCULAR EMISIONES DE N2O DE SUELO
GET http://localhost:3000/calculate-n2o-direct-emissions/soils
Content-Type: application/json

{
"FS_N_F_ON_CONDITIONS": [
{
    "F_SN": 1000,
    "F_ON": 500,
    "EF_1i": 0.1
},
{
    "F_SN": 800,
    "F_ON": 300,
    "EF_1i": 0.015
}
],
"F_CR": 700,
"F_SOM": 400,
"EF_1": 0.02,
"N2O_N_OS_CONDITIONS": [
{
    "F_OS": 200,
    "EF_2": 0.03,
    "type": "CG,Temp"
},
{
    "F_OS": 150,
    "EF_2": 0.025,
    "type": "F,Trop"
}
],
"N2O_N_PRP_CONDITIONS": [
{
    "F_PRP": 100,
    "EF3_PRP": 0.02,
    "type": "CPP"
},
{
    "F_PRP": 80,
    "EF3_PRP": 0.015,
    "type": "SO"
}
]
}

###OBTENER DATOS HISTORICOS SEGUN PARAMETROS
GET http://localhost:3000/data/historical-emissions
Content-Type: application/json

{
  "country": "Mexico",
  "year": "2004"
}



###FUNCION
GET http://localhost:3000/calculate-n2o-direct-emissions/soils
Content-Type: application/json

{
  "FS_N_F_ON_CONDITIONS": [
    {
      "F_SN": "100",
      "F_ON": "500",
      "EF_1i": "0.004"
    }
  ],
  "F_CR": "22",
  "F_SOM": "112222",
  "EF_1": 0.01,
  "N2O_N_OS_CONDITIONS": [
    {
      "EF_2": "0.22",
      "type": "trop",
      "F_OS": "121"
    },
    {
      "EF_2": "3.6",
      "type": "peatland-tropical"
    },
    {
      "EF_2": "3.6",
      "type": "peatland-tropical",
      "F_OS": "1"
    },
    {
      "EF_2": "3.6",
      "type": "peatland-tropical",
      "F_OS": "12"
    },
    {
      "EF_2": "3.6",
      "type": "peatland-tropical",
      "F_OS": "121"
    }
  ],
  "N2O_N_PRP_CONDITIONS": [
    {
      "EF_2": "0.003",
      "type": "ship"
    },
    {
      "EF_2": "0.003",
      "type": "ship",
      "F_PRP": "77"
    }
  ]
}


###OBTENER DATOS HISTORICOS SEGUN PARAMETROS
GET http://localhost:3000/data/historical-emissions/gas
Content-Type: application/json

{
  "country": "Mexico",
  "year": "2004"
}
